
public class EvenFibonacciNumbers {

	public static void main(String[] args) {
		// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
		int n1=0;
		int n2=1;
		int m;
		int sum = 0;
		//System.out.println(n1 + "," + " "+n2);
		for (int i = 2; i<10;i++){
	
			m= n1 + n2;
			if (m%2 == 0){
			System.out.println(" " + m);
			sum = sum  + m;
			}
			n1 = n2;
			n2 = m;
			
			
			
			
			
		}
		
		System.out.println("the sum is :" + sum);
			 
		
		}
	
	
	
		
	}


